#
# Persistent Volume
#
apiVersion: v1
kind: PersistentVolume                        # Create a PV
metadata:
  name: backend-pv
spec:
  storageClassName: manual                    # Storage class. A PV Claim requesting the same storageClass can be bound to this volume.
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteMany
  hostPath:                                   # a file/directory on the Node to emulate network-attached storage
    path: /Users/appleuser/scrap_project/backend
  # persistentVolumeReclaimPolicy: Retain       # Retain the PV even after PVC is deleted.
---
#
# Persistent Volume Claim
#
apiVersion: v1
kind: PersistentVolumeClaim                   # Create a PersistentVolumeClaim to request a PersistentVolume storage
metadata:                                     # Claim name and labels
  name: backend-pvc
  labels:
    io.kompose.service: backend-pvc
spec:                                         # Access mode and resource limits
  storageClassName: manual                    # Request a certain storage class
  accessModes:
    - ReadWriteMany                           # ReadWriteMany means the volume can be mounted as read-write by many Nodes
  resources:
    requests:
      storage: 256Mi


# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   labels:
#     io.kompose.service: backend-claim0
#   name: backend-claim0
# spec:
#   resources:
#     requests:
#       storage: 100Mi
#   accessModes:
#   - ReadWriteOnce
#   storageClassName: local-storage
#   # local:
#   #   path: /Users/appleuser/scrap_project/backend
