apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/scrap-project-default: "true"
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_ROOT_PASSWORD
            - name: MONGO_INITDB_ROOT_USERNAME
            - name: SECRET_KEY
            - name: TWITTER_ACCESS_SECRET
            - name: TWITTER_ACCESS_TOKEN
            - name: TWITTER_API_KEY
            - name: TWITTER_API_SECRET
            - name: TWITTER_BEARER_TOKEN
          image: v02202/scrape_project:1.0.2
          imagePullPolicy: IfNotPresent
          name: backend-container
          ports:
            - containerPort: 5000
              hostPort: 5000
              protocol: TCP
          volumeMounts:
            - mountPath: /backend-code
              name: backend-claim0
      restartPolicy: Always
      volumes:
        - name: backend-claim0
          persistentVolumeClaim:
            claimName: backend-claim0
